In [1]:
! pip install numpy

In [2]:
import numpy as np
a=np.array([[1,2,3,4,5,6,7] ])
print(type(a))

<class 'numpy.ndarray'>


In [3]:

a.shape

(1, 7)

In [4]:
a[0,6]

7

In [5]:
a=[[1,2,3,4,5,6,7]]
b=np.array(a)
b

array([[1, 2, 3, 4, 5, 6, 7]])

In [6]:
c=a+b
c

array([[ 2,  4,  6,  8, 10, 12, 14]])

In [7]:
import numpy as np
a=np.arange(15).reshape(5,3)
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [8]:
import numpy as np
a=np.linspace(10,20,2)
print(a)
b=np.logspace(0,10,5,base=2)
print(b)



[10. 20.]
[1.00000000e+00 5.65685425e+00 3.20000000e+01 1.81019336e+02
 1.02400000e+03]


In [9]:
import numpy as np
g=np.full((2,4),fill_value=10)
g



array([[10, 10, 10, 10],
       [10, 10, 10, 10]])

In [10]:
import numpy as np
a=np.arange(6).reshape(2,3)
a


array([[0, 1, 2],
       [3, 4, 5]])

In [11]:
import numpy as np
a=np.zeros((3,3))
a

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [12]:
import numpy as np
a=np.ones((3,3))
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [13]:
import numpy as np
a=np.empty((4,4))
a

array([[4.67296746e-307, 1.69121096e-306, 1.29061074e-306,
        1.69119873e-306],
       [1.78019082e-306, 8.34441742e-308, 1.78022342e-306,
        6.23058028e-307],
       [9.79107872e-307, 6.89807188e-307, 7.56594375e-307,
        6.23060065e-307],
       [1.78021527e-306, 8.34454050e-308, 1.11261027e-306,
        2.04712907e-306]])

In [14]:
from scipy import misc

img = misc.face()
img

array([[[121, 112, 131],
        [138, 129, 148],
        [153, 144, 165],
        ...,
        [119, 126,  74],
        [131, 136,  82],
        [139, 144,  90]],

       [[ 89,  82, 100],
        [110, 103, 121],
        [130, 122, 143],
        ...,
        [118, 125,  71],
        [134, 141,  87],
        [146, 153,  99]],

       [[ 73,  66,  84],
        [ 94,  87, 105],
        [115, 108, 126],
        ...,
        [117, 126,  71],
        [133, 142,  87],
        [144, 153,  98]],

       ...,

       [[ 87, 106,  76],
        [ 94, 110,  81],
        [107, 124,  92],
        ...,
        [120, 158,  97],
        [119, 157,  96],
        [119, 158,  95]],

       [[ 85, 101,  72],
        [ 95, 111,  82],
        [112, 127,  96],
        ...,
        [121, 157,  96],
        [120, 156,  94],
        [120, 156,  94]],

       [[ 85, 101,  74],
        [ 97, 113,  84],
        [111, 126,  97],
        ...,
        [120, 156,  95],
        [119, 155,  93],
        [118, 154,  92]]

In [15]:
a=np.identity(6)
a

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [16]:
a
b=np.sort(a)
b

array([[0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 1.]])

In [14]:
import numpy as np
x1= [[1,2,3,4,4,5,6]
     ,[1,2,3,4,5,6,7]]

x2=[[1,2,3,4,4,5,6],
    [1,2,3,4,5,6,7] ]
a=np.array((x1))
b=np.array((x2))
c=np.multiply(a,b)
c




array([[ 1,  4,  9, 16, 16, 25, 36],
       [ 1,  4,  9, 16, 25, 36, 49]])

In [17]:
A = np.array([[-1,-3,-4],[-2,-4,-3]])
np.abs(A)

array([[1, 3, 4],
       [2, 4, 3]])

In [19]:
a = np.array([1,2,3,4,5])
b = np.array([1,4,9,16,25])
np.hstack((a,b))

array([ 1,  2,  3,  4,  5,  1,  4,  9, 16, 25])

In [2]:
import numpy as np
a = np.array([1,2,3,4,5])
b = np.array([1,4,9,16,25])
c=np.vstack((a,b))
c


array([[ 1,  2,  3,  4,  5],
       [ 1,  4,  9, 16, 25]])